//
//  LFSPallateColor.swift
//  LifeupSnap
//
//  Created by lifeup on 13/12/2561 BE.
//  Copyright © 2561 Khwan Siricharoenporn. All rights reserved.
//

import UIKit

internal struct LFSPallateColor {
    var colors: [LFSColor]
    
    init() {
        colors = [LFSColor]()
        generateColor()
    }
    
    private mutating func generateColor() {
        self.colors.append(LFSColor(name: "Black", color: UIColor.black.withAlphaComponent(0.6)))
        self.colors.append(LFSColor(name: "Dark Gray", color: UIColor.darkGray.withAlphaComponent(0.6)))
        //self.colors.append(LFSColor(name: "Light Gray", color: UIColor.lightGray.withAlphaComponent(0.6)))
        self.colors.append(LFSColor(name: "White", color: UIColor.white.withAlphaComponent(0.6)))
        self.colors.append(LFSColor(name: "Gray", color: UIColor.gray.withAlphaComponent(0.6)))
        self.colors.append(LFSColor(name: "Red", color: UIColor.red.withAlphaComponent(0.6)))
        self.colors.append(LFSColor(name: "Green", color: UIColor.green.withAlphaComponent(0.6)))
        self.colors.append(LFSColor(name: "Red", color: UIColor.red.withAlphaComponent(0.6)))
        self.colors.append(LFSColor(name: "Blue", color: UIColor.blue.withAlphaComponent(0.6)))
        self.colors.append(LFSColor(name: "Cyan", color: UIColor.cyan.withAlphaComponent(0.6)))
        self.colors.append(LFSColor(name: "Yellow", color: UIColor.yellow.withAlphaComponent(0.6)))
        self.colors.append(LFSColor(name: "Magenta", color: UIColor.magenta.withAlphaComponent(0.6)))
        self.colors.append(LFSColor(name: "Orange", color: UIColor.orange.withAlphaComponent(0.6)))
        self.colors.append(LFSColor(name: "Purple", color: UIColor.purple.withAlphaComponent(0.6)))
        self.colors.append(LFSColor(name: "Brown", color: UIColor.brown.withAlphaComponent(0.6)))
        
        //MARK: RGB
//        self.colors.append(LFSColor(name: "Honey Dew", color: UIColor(red: 240, green: 255, blue: 240, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Mint Cream", color: UIColor(red: 245, green: 255, blue: 250, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Azure", color: UIColor(red: 240, green: 255, blue: 255, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Alice Blue", color: UIColor(red: 240, green: 248, blue: 255, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Ghost White", color: UIColor(red: 248, green: 248, blue: 255, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Sea Shell", color: UIColor(red: 255, green: 245, blue: 238, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Beige", color: UIColor(red: 245, green: 245, blue: 220, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Ol dLace", color: UIColor(red: 253, green: 245, blue: 230, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Floral White", color: UIColor(red: 255, green: 250, blue: 240, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "White Smoke", color: UIColor(red: 245, green: 245, blue: 245, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Gains bora", color: UIColor(red: 220, green: 220, blue: 220, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Silver", color: UIColor(red: 192, green: 192, blue: 192, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Light State Gray", color: UIColor(red: 119, green: 136, blue: 153, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "State Gray", color: UIColor(red: 112, green: 128, blue: 144, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Dim Gray", color: UIColor(red: 105, green: 105, blue: 105, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Dark State Gray", color: UIColor(red: 47, green: 79, blue: 79, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Sky Blue", color: UIColor(red: 135, green: 206, blue: 235, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Light Sky Blue", color: UIColor(red: 135, green: 206, blue: 250, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Deep Sky Blue", color: UIColor(red: 0, green: 191, blue: 255, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Dodger Blue", color: UIColor(red: 30, green: 144, blue: 255, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Royal Blue", color: UIColor(red: 65, green: 105, blue: 225, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "State Blue", color: UIColor(red: 106, green: 90, blue: 205, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Medium Blue", color: UIColor(red: 0, green: 0, blue: 205, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Indigo", color: UIColor(red: 75, green: 0, blue: 130, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Dark Blue", color: UIColor(red: 0, green: 0, blue: 139, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Navy", color: UIColor(red: 0, green: 0, blue: 128, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Light Cyan", color: UIColor(red: 224, green: 255, blue: 255, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Pale Turquoise", color: UIColor(red: 175, green: 238, blue: 238, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Power Blue", color: UIColor(red: 176, green: 224, blue: 230, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Aquamarine", color: UIColor(red: 127, green: 255, blue: 212, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Turquoise", color: UIColor(red: 64, green: 224, blue: 208, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Medium Turquoise", color: UIColor(red: 72, green: 209, blue: 204, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Dark Turquoise", color: UIColor(red: 0, green: 206, blue: 209, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Steel Blue", color: UIColor(red: 70, green: 130, blue: 180, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Dark State Blue", color: UIColor(red: 72, green: 61, blue: 139, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Midnight Blue", color: UIColor(red: 25, green: 25, blue: 112, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Light Green", color: UIColor(red: 144, green: 238, blue: 144, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Medium Spring", color: UIColor(red: 0, green: 250, blue: 154, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Medium Aquamarine", color: UIColor(red: 102, green: 205, blue: 170, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Dark Sea Green", color: UIColor(red: 143, green: 188, blue: 143, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Light Sea Green", color: UIColor(red: 32, green: 178, blue: 170, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Medium Sea Green", color: UIColor(red: 60, green: 179, blue: 113, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Sea Green", color: UIColor(red: 46, green: 139, blue: 87, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Forest Green", color: UIColor(red: 34, green: 139, blue: 34, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Dark Cyan", color: UIColor(red: 0, green: 139, blue: 139, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Cadet Blue", color: UIColor(red: 95, green: 158, blue: 160, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Teal", color: UIColor(red: 0, green: 128, blue: 128, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Green Yellow", color: UIColor(red: 173, green: 255, blue: 47, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Chatreuse", color: UIColor(red: 127, green: 255, blue: 0, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Lawn Green", color: UIColor(red: 124, green: 252, blue: 0, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Lime", color: UIColor(red: 0, green: 255, blue: 0, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Yellow Green", color: UIColor(red: 154, green: 205, blue: 50, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Lime Green", color: UIColor(red: 50, green: 205, blue: 50, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Olive", color: UIColor(red: 128, green: 128, blue: 0, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Olive Drab", color: UIColor(red: 107, green: 142, blue: 35, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Green", color: UIColor(red: 0, green: 128, blue: 0, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Dark Green", color: UIColor(red: 0, green: 100, blue: 0, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Dark Olive Green", color: UIColor(red: 85, green: 107, blue: 47, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Corn Silk", color: UIColor(red: 255, green: 248, blue: 220, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Blanched Almond", color: UIColor(red: 255, green: 235, blue: 205, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Bisque", color: UIColor(red: 255, green: 228, blue: 196, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Wheat", color: UIColor(red: 245, green: 222, blue: 179, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Burly Wood", color: UIColor(red: 222, green: 184, blue: 135, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Tan", color: UIColor(red: 210, green: 180, blue: 140, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Rosy Brown", color: UIColor(red: 188, green: 143, blue: 143, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Snady Brown", color: UIColor(red: 244, green: 165, blue: 32, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Dark Goldenrod", color: UIColor(red: 184, green: 134, blue: 11, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Peru", color: UIColor(red: 205, green: 133, blue: 63, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Linen", color: UIColor(red: 250, green: 240, blue: 230, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Navajo White", color: UIColor(red: 255, green: 222, blue: 173, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Light Salmon", color: UIColor(red: 255, green: 160, blue: 122, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Dark Salmon", color: UIColor(red: 233, green: 150, blue: 122, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Light Coral", color: UIColor(red: 240, green: 128, blue: 128, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Salmon", color: UIColor(red: 250, green: 128, blue: 114, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Coral", color: UIColor(red: 255, green: 127, blue: 80, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Tomato", color: UIColor(red: 255, green: 99, blue: 71, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Indian Red", color: UIColor(red: 205, green: 92, blue: 92, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Crimson", color: UIColor(red: 220, green: 20, blue: 60, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Dark Orange", color: UIColor(red: 255, green: 140, blue: 0, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Orange Red", color: UIColor(red: 255, green: 69, blue: 0, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Chocolate", color: UIColor(red: 210, green: 105, blue: 30, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Sieanna", color: UIColor(red: 160, green: 82, blue: 45, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Saddle Brown", color: UIColor(red: 139, green: 69, blue: 19, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Fire Brick", color: UIColor(red: 178, green: 34, blue: 34, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Dark Red", color: UIColor(red: 139, green: 0, blue: 0, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Maroon", color: UIColor(red: 128, green: 0, blue: 0, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Misty Rose", color: UIColor(red: 255, green: 228, blue: 225, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Pink", color: UIColor(red: 255, green: 192, blue: 203, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Light Pink", color: UIColor(red: 255, green: 182, blue: 193, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Plum", color: UIColor(red: 221, green: 160, blue: 221, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Violet", color: UIColor(red: 238, green: 139, blue: 238, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Orchid", color: UIColor(red: 218, green: 112, blue: 214, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Hot Pink", color: UIColor(red: 255, green: 105, blue: 180, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Pale Violet Red", color: UIColor(red: 219, green: 112, blue: 147, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Deep Pink", color: UIColor(red: 255, green: 20, blue: 147, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Medium Violet Red", color: UIColor(red: 199, green: 21, blue: 133, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Thistle", color: UIColor(red: 216, green: 191, blue: 216, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Light Steel Blue", color: UIColor(red: 176, green: 196, blue: 222, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Cornflower Blue", color: UIColor(red: 100, green: 149, blue: 237, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Medium State Blue", color: UIColor(red: 123, green: 149, blue: 237, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Medium Purple", color: UIColor(red: 147, green: 112, blue: 219, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Medium Orchid", color: UIColor(red: 186, green: 85, blue: 211, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Dark Orchid", color: UIColor(red: 153, green: 50, blue: 204, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Blue Violet", color: UIColor(red: 138, green: 43, blue: 226, alpha: 0.6)))
//        self.colors.append(LFSColor(name: "Dark Magenta", color: UIColor(red: 139, green: 0, blue: 139, alpha: 0.6)))
    }
}
